### ISSUE TITLE
flag "-file" begins with -

### ISSUE THREAD

**Issue by ctaggart** [dolmen-go/docker-list-context#1]
I get an error when running. A fix is to comment out this line.

![image](https://user-images.githubusercontent.com/80104/130332629-c0030f6c-6636-4be0-b10e-18151d54d679.png)

**Comment by dolmen** [comment]
As `--file` is [accepted](https://pkg.go.dev/flag#hdr-Command_line_flag_syntax) even if the flag is declared just with `"file"` I will just remove the `"-"` (that was useful for documentation to match Docker CLI syntax).

**Comment by dolmen** [comment]
Fixed by 7920b2911aaa320c26dad0f13ecab9993db1eee3.
